import datetime
import queue
from abc import ABCMeta, abstractmethod

from event import FillEvent, OrderEvent
from config import STRATEGY_PARAMS, BACKTEST_CONFIG, logger

class ExecutionHandler(object):
    """
    The ExecutionHandler abstract class handles the interaction
    between a set of order objects generated by a Portfolio and
    the ultimate set of Fill objects that actually occur in the
    market. 
    """
    __metaclass__ = ABCMeta

    @abstractmethod
    def execute_order(self, event):
        """
        Takes an Order event and executes it, producing
        a Fill event that gets placed onto the Events queue.
        """
        raise NotImplementedError("Should implement execute_order()")

class SimulatedExecutionHandler(ExecutionHandler):
    """
    A simulated execution handler that takes OrderEvents and 
    immediately fills them using the current bar's close price.
    """

    def __init__(self, events, bars):
        """
        Parameters:
        events - The Event Queue.
        bars - The DataHandler object.
        """
        self.events = events
        self.bars = bars

    def execute_order(self, event):
        """
        Takes an Order event and executes it, producing
        a Fill event that gets placed onto the Events queue.
        """
        if event.type == 'ORDER':
            # Slippage & Commission
            commission_rate = STRATEGY_PARAMS.get('commission_rate', 0.0002)
            slippage = BACKTEST_CONFIG.get('slippage', 0.0)
            
            fill_datetime = self.bars.get_latest_bar_datetime(event.symbol)
            fill_price = self.bars.get_latest_bar_value(event.symbol, "close")
            
            # 1. Apply Slippage (0.0 per user requirement)
            if event.direction == 'BUY':
                fill_price += slippage
            else:
                fill_price -= slippage
                
            # 2. Calculate Costs
            quantity = event.quantity
            multiplier = 300.0
            fill_cost = quantity * fill_price * multiplier
            commission = fill_cost * commission_rate
            
            fill_event = FillEvent(
                fill_datetime, event.symbol, 
                'CFFEX', quantity, event.direction, fill_cost, commission
            )
            self.events.put(fill_event)
            logger.info(f"Order Executed: {event.direction} {quantity} {event.symbol} @ {fill_price:.2f}, Commission: {commission:.2f}")
