import datetime
import numpy as np
import pandas as pd
from abc import ABCMeta, abstractmethod
import queue
import os
from event import SignalEvent

class Strategy(object):
    """
    Strategy is an abstract base class providing an interface for
    all subsequent (inherited) strategy objects.

    The goal of a (derived) Strategy object is to generate Signal
    objects for particular symbols based on the inputs of Bars 
    (OHLCV) generated by a DataHandler object.
    """
    __metaclass__ = ABCMeta

    @abstractmethod
    def calculate_signals(self):
        """
        Provides the mechanisms to calculate the signals of the strategy.
        """
        raise NotImplementedError("Should implement calculate_signals()")


from config import STRATEGY_PARAMS, logger
from event import SignalEvent


class ConsistencyStrategy(Strategy):
    """
    Reproduces the 'Constituent Consistency' CTA strategy from Guangfa Securities.
    """

    def __init__(self, bars, events):
        """
        Parameters:
        bars - The DataHandler object that provides bar information.
        events - The Event Queue object.
        """
        self.bars = bars
        self.symbol_list = self.bars.symbol_list
        self.events = events
        
        # Use centralized config (P3)
        self.T_minutes = STRATEGY_PARAMS['T_minutes']
        self.window_L = STRATEGY_PARAMS['window_L']
        self.threshold_window = STRATEGY_PARAMS['threshold_window']

        # P2 Improvement: Use list for O(1) appending and access
        self.r_history_list = []
        
        self.last_signal_date = None

    def _calculate_consistency_indicator(self, current_date):
        """
        Fetches the pre-calculated R value for today for the specific T_minutes.
        """
        if hasattr(self.bars, 'alpha_daily_df') and self.bars.alpha_daily_df is not None:
            df = self.bars.alpha_daily_df
            col = f'R_{self.T_minutes}'
            if current_date in df.index and col in df.columns:
                return df.loc[current_date, col]
        return None

    def _get_threshold(self, current_date):
        """
        Calculates threshold as the mean of R values at moment T over the last X trading days.
        """
        if hasattr(self.bars, 'alpha_daily_df') and self.bars.alpha_daily_df is not None:
            df = self.bars.alpha_daily_df
            col = f'R_{self.T_minutes}'
            # Get historical values up to but NOT including today
            history = df.loc[:current_date].iloc[:-1]
            if len(history) >= self.threshold_window:
                recent_vals = history[col].tail(self.threshold_window)
                return recent_vals.mean()
        return 60.0 # Default fallback

    def calculate_signals(self, event):
        if event.type == 'MARKET':
            cur_time = self.bars.get_latest_bar_datetime('IF')
            if cur_time is None: return
            
            cur_date = cur_time.date()
            cur_date_ts = pd.Timestamp(cur_date) # For DF lookup
            
            # Market open is 09:30
            target_time = datetime.datetime.combine(cur_date, datetime.time(9, 30)) + \
                          datetime.timedelta(minutes=self.T_minutes)
            
            if cur_time == target_time and self.last_signal_date != cur_date:
                R = self._calculate_consistency_indicator(cur_date_ts)
                if R is not None and not pd.isna(R):
                    threshold = self._get_threshold(cur_date_ts)
                    
                    if R > threshold:
                        history = self.bars.get_latest_bars('IF', N=self.T_minutes+1)
                        if len(history) >= self.T_minutes + 1:
                            price_t0 = history[0].open # 09:30 open
                            price_T = history[-1].close # T-min close
                            signal_type = 'LONG' if price_T > price_t0 else 'SHORT'
                                
                            signal = SignalEvent('IF', cur_time, signal_type)
                            self.events.put(signal)
                            self.last_signal_date = cur_date
                            logger.info(f"Signal Generated: {cur_date} {signal_type} R={R:.2f} Thresh={threshold:.2f}")
